### ISSUE TITLE
Error after deleting calendar in korganizer

### ISSUE THREAD

**Issue by derirremitderwaffe** [etesync/etesync-dav#107] opened 2020-01-10 11:10 UTC
Hi, I added some calendars via the etesync-dav bridge in korganizer. As I deleted the "Default" calendar  the webui stopped working.

I could login, but it showed:
`Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

console output from debug shows:
```
Jan 10 11:45:46 julius-pc etesync-dav[17730]: Traceback (most recent call last):
Jan 10 11:45:46 julius-pc etesync-dav[17730]:   File "/usr/lib/python3.8/site-packages/etesync_dav/radicale/storage.py", line 54, in run
Jan 10 11:45:46 julius-pc etesync-dav[17730]:     etesync.sync()
Jan 10 11:45:46 julius-pc etesync-dav[17730]:   File "/usr/lib/python3.8/site-packages/etesync/api.py", line 107, in sync
Jan 10 11:45:46 julius-pc etesync-dav[17730]:     self.sync_journal_list()
Jan 10 11:45:46 julius-pc etesync-dav[17730]:   File "/usr/lib/python3.8/site-packages/etesync/api.py", line 112, in sync_journal_list
Jan 10 11:45:46 julius-pc etesync-dav[17730]:     self.push_journal_list()
Jan 10 11:45:46 julius-pc etesync-dav[17730]:   File "/usr/lib/python3.8/site-packages/etesync/api.py", line 157, in push_journal_list
Jan 10 11:45:46 julius-pc etesync-dav[17730]:     manager.delete(raw_journal)
Jan 10 11:45:46 julius-pc etesync-dav[17730]:   File "/usr/lib/python3.8/site-packages/etesync/service.py", line 187, in delete
Jan 10 11:45:46 julius-pc etesync-dav[17730]:     self._validate_response(response)
Jan 10 11:45:46 julius-pc etesync-dav[17730]:   File "/usr/lib/python3.8/site-packages/etesync/service.py", line 149, in _validate_response
Jan 10 11:45:46 julius-pc etesync-dav[17730]:     raise exceptions.HttpNotFound(response.status_code)
Jan 10 11:45:46 julius-pc etesync-dav[17730]: etesync.exceptions.HttpNotFound: 404
```

Android app worked alright. After deleting the whole ~/.config/etesync-dav  folder and adding my account again all did work again

**Comment by tasn** [comment] 2020-01-11 09:57
Great to hear that you got it to work again. :)

As for the issue, could you please walk me step by step what you did and how exactly? E.g., I created a new calendar from the Android app, then I remove the old calendar from Evolution (through etesync-dav) and etc? I'd love to be able to reproduce it locally before I jump into investigating.

Thanks for the report!

**Comment by derirremitderwaffe** [comment] 2020-01-11 19:28
Sadly I cant reproduced it, again.
But i found some other things.
In the android app, i deleted all calendars, synced and it generated 5 new 'Default' calendars, as I repeatet it, i got four 'Default' calendars.

Also the webui only works for me if i start with '-f' flag for foreground. 
Debugmode works with '-D' flag, but ` * Debug mode: off
` is always shown upon start in the console output.

If I start it as `python -m pdb /usr/bin/etesync-dav`, the webui works as long as I execute the 'exit' command.  
`[julius@julius-pc ~]$ ps afx |grep ete
  131 ?        I<     0:00  \_ [nvme-delete-wq]
 5891 pts/3    S+     0:00              \_ grep --colour=auto ete
 5787 ?        Ss     0:00 python -m pdb /usr/bin/etesync-dav
`
`[julius@julius-pc ~]$ netstat -tulpen
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 127.0.0.1:37358         0.0.0.0:*               LISTEN      1000       148188     5787/python         
tcp        1      0 127.0.0.1:37359         0.0.0.0:*               LISTEN      1000       146885     5787/python    `
etesync-dav runs on, the dav bridge is useable from the korganizer client, but the webui wont load

**Comment by tasn** [comment] 2020-01-12 08:14
Deleting all of the calendars on the Android app: it shouldn't let you do that. It should prevent you from deleting the last one. Is it not the case? Could you try again?

Webui: what platform are you talking about?
`* Debug mode: off` is fine, you can ignore that. This is referring to the debug mode of the web management, rather than the dav bridge. We can't turn this message off unfortunately. :|

`exit` only kills the main thread I guess, so the other threads still live even when you exit.

systemd file: this is weird. Foreground is the default...

Btw, please use triple backticks when pasting multiline pastes. I edited your comment so you can see what I mean. The single backtick is for inline code and it mangles multiline snippets.

**Comment by derirremitderwaffe** [comment] 2020-01-12 11:38
I recorded a screenvideo in Android:
[recording_20200112_120200.zip](https://github.com/etesync/etesync-dav/files/4050576/recording_20200112_120200.zip)

plattform is manjaro linux, i installed etesync-dav via Arch User Packages
```
[julius@julius-pc ~]$ pacman -Qi etesync-dav
Name                     : etesync-dav
Version                  : 0.14.0-1

```
```
[julius@julius-pc ~]$ python --version
Python 3.8.1
```

by starting from console without any flags, I'm getting this:
```
[julius@julius-pc ~]$ etesync-dav 
 * Serving Flask app "etesync_dav.webui" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:37359/ (Press CTRL+C to quit)
[julius@julius-pc ~]$ 


```
The output detaches immediately and the program runs in background.

**Comment by tasn** [comment] 2020-01-12 11:45
Android issue: weird, I'll take a look into that. Could you please open a ticket in https://github.com/etesync/android ?

As for the daemonise issue: I'm running arch, so should be very similar to you. I'm also the maintainer of the AUR package, and it works for me here. I just installed the aur package again from scratch and tried it out again, and it works as expected. It runs in the foreground.

If you run etesync-dav with -D, does it show anything about trying to load a config file? Maybe you have a radicale configuration file (etesync is based on radicale) that explicitly states it should run in the background, and for some reason etesync-dav is loading that.

**Comment by derirremitderwaffe** [comment] 2020-01-12 13:39
```
[julius@julius-pc ~]$ etesync-dav -D
 * Serving Flask app "etesync_dav.webui" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:37359/ (Press CTRL+C to quit)
[7fb647fbe740] INFO: Starting Radicale
[7fb647fbe740] INFO: Authentication type is 'htpasswd'
[7fb647fbe740] INFO: Storage type is 'etesync_dav.radicale.storage'
[7fb647fbe740] INFO: Rights type is 'etesync_dav.radicale.rights'
[7fb647fbe740] INFO: Web type is 'etesync_dav.radicale.web'
[7fb647fbe740] INFO: Listening to 'localhost' on port 37358
[julius@julius-pc ~]$ 
```
-D is sadly not very verbose it says nothing about configs

```
[julius@julius-pc ~]$ inotifywait -mr -e access ~/.config/etesync-dav/
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/home/julius/.config/etesync-dav/ ACCESS htpaswd
/home/julius/.config/etesync-dav/ ACCESS etesync_creds


```

> Maybe you have a radicale configuration file (etesync is based on radicale) that explicitly states it should run in the background, and for some reason etesync-dav is loading that.

Indeed it seems, changing my /etc/radicale/config   `# Daemon flag
daemon = True
` to `# Daemon flag
daemon = False
`
changes the behavior, so that it wont detach and the webui is working fine.



Strace show's that my users radicale config as also the config in /etc is read.


`[julius@julius-pc ~]$ strace -e trace=file -o strace -ff etesync-dav`
```
[julius@julius-pc ~]$ find ./ -iname 'strace.2*' -print0 |xargs -0 grep /radicale/config
find: ‘./.cache/yay/gprbuild/pkg’: Keine Berechtigung
find: ‘./.cache/yay/shiboken/pkg’: Keine Berechtigung
./strace.25141:stat("/usr/lib/python3.8/site-packages/radicale/config.py", {st_mode=S_IFREG|0644, st_size=9402, ...}) = 0
./strace.25141:stat("/usr/lib/python3.8/site-packages/radicale/config.py", {st_mode=S_IFREG|0644, st_size=9402, ...}) = 0
./strace.25141:openat(AT_FDCWD, "/usr/lib/python3.8/site-packages/radicale/config.py", O_RDONLY|O_CLOEXEC) = 3
./strace.25141:openat(AT_FDCWD, "/etc/radicale/config", O_RDONLY|O_CLOEXEC) = 4
./strace.25141:openat(AT_FDCWD, "/home/julius/.config/radicale/config", O_RDONLY|O_CLOEXEC) = -1 ELOOP (Zu viele Ebenen aus symbolischen Links)
./strace.25114:stat("/usr/lib/python3.8/site-packages/radicale/config.py", {st_mode=S_IFREG|0644, st_size=9402, ...}) = 0
./strace.25114:stat("/usr/lib/python3.8/site-packages/radicale/config.py", {st_mode=S_IFREG|0644, st_size=9402, ...}) = 0
./strace.25114:openat(AT_FDCWD, "/usr/lib/python3.8/site-packages/radicale/config.py", O_RDONLY|O_CLOEXEC) = 3
./strace.25114:openat(AT_FDCWD, "/etc/radicale/config", O_RDONLY|O_CLOEXEC) = 4
./strace.25114:openat(AT_FDCWD, "/home/julius/.config/radicale/config", O_RDONLY|O_CLOEXEC) = -1 ELOOP (Zu viele Ebenen aus symbolischen Links)
```
**/strace.25114:openat(AT_FDCWD, "/etc/radicale/config", O_RDONLY|O_CLOEXEC) = 4**
**./strace.25141:openat(AT_FDCWD, "/home/julius/.config/radicale/config",**

**Comment by tasn** [comment] 2020-01-12 17:14
OK, so for some reason we are reading the radicale config. I wonder if there's a way to force it not to. Anyhow, I opened #108 to track this issue.

I'm closing this issue because it seems like everything here was either resolved or moved to another ticket. Please let me know if there's still something wrong, and I'll reopen it.

Thanks for all the info!

**Closed by tasn** 2020-01-12 17:14 UTC
