### ISSUE TITLE
Offer etesync-dav via the package manager "Homebrew" for macOS and Linux

### ISSUE THREAD

**Issue by porg** [etesync/etesync-dav#57] opened 2019-04-10 11:02 UTC
**Main Goal:**
- `brew install etesync-dav` installs everything you need for running etesync on macOS or Linux, inlcuding manpages and any helpers and dependencies.

**Additional goals:** (split into separate tickets if needed/approporiate)
1. ~OS specific mechanism for automatically starting etesync-dav with the system start. Either for all users and/or per user login (running in user space) whatever is appropriate to etesync's architecture.~ - moved to #58
2. `brew uninstall etesync-dav` uninstalls the executables, manpages, etc.
3. #59
4. Facilitate the capacity of `brew [ install | upgrade | uninstall ] etesync-dav` to print accompanying infos at the end of the output.

Brew does this per package in a section called "Caveats", i.e.
> ==> Caveats
> ==> syncthing
> To have launchd start syncthing now and restart at login:
>   brew services start syncthing
> Or, if you don't want/need a background service you can just run:
>   syncthing

For etesync this could be something like:
> Next run etesync manage add your-username@domain.com

And if running `brew uninstall etesync-dav` depending how #59 gets implemented, you could inform that user-data was auto-deleted as part of the uninstallation or if that is not done, where the remaining user-data resides, if the careful users wants to wipe that clean too.

**Comment by tasn** [comment] 2019-04-12 12:22
Thanks for opening this ticket and the additional ideas. I moved the first 1 to its own ticket, though if you could move the 3rd to its own ticket too that would be great (just the user data deletion). These don't have anything to do with this task. :)

**Comment by porg** [comment] 2019-04-12 19:30
I split this ticket according to your request.

**Comment by tasn** [comment] 2019-04-14 11:14
Thanks.

**Comment by porg** [comment] 2019-04-16 19:40
Added nr. 4  to the "Additional Goals"

**Comment by tasn** [comment] 2019-04-29 09:36
Duplicate of #50. Thanks @porg.

**Closed by tasn** 2019-04-29 09:36 UTC

**Comment by plsnotracking** [comment] 2020-09-18 20:44
@tasn @porg I'm definitely missing something here

```
❯ brew install etesync-dav
Updating Homebrew...
Error: No available formula with the name "etesync-dav"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

It'd be great if you guys could help me figure that, thank you.

**Comment by porg** [comment] 2020-09-18 20:52
You did not read properly. This issue was a **proposal** to offer etesync-dav via a package manager on macOS such as brew. It is not implemented until today! Progress can be tracked in the original issue #50.
