### ISSUE TITLE
cannot sync contacts in Cardbook (Thundebird)

### ISSUE THREAD

**Issue by arsylum** [etesync/etesync-dav#65] opened 2019-04-17 12:53 UTC
I tried to set etesync in a new Thunderbird profile. Calendar is working in Lightning. But when I try do add a new address book in Cardbook there are 2 issues:
* In the Cardbook new address book wizard, after configuring URL and login credentials, my contact books show up but the only cardDav version that I can choose for any of them is 3.0
* After I create the existing contact book, nothing is ever synced

With a fresh contact book I can in fact create and sync contacts in CardBook. The problem might be the incompability of cardDav v3 and v4

maybe related:
```xml
2019.04.17 14:35:59:367 : Discovery module : debug mode : response code : (new Number(207))
2019.04.17 14:35:59:391 : Discovery module : debug mode : response text : (new String("

<?xml version='1.0' encoding='utf-8'?>
<multistatus
	xmlns=\"DAV:\"
	xmlns:CR=\"urn:ietf:params:xml:ns:carddav\">
	<response>
		<href>/foo%40posteo.de/ffd8ec50876xxxxxxxxxxxxxxxxxxxxxx59bf9c78f4e191/</href>
		<propstat>
			<prop />
			<status>HTTP/1.1 200 OK</status>
		</propstat>
		<propstat>
			<prop>
				<CR:supported-address-data />
			</prop>
			<status>HTTP/1.1 404 Not Found</status>
		</propstat>
	</response>
	<response>
		<href>/foo%40posteo.de/ffd8ec5087xxxxxxxxxxxxxxxxxxxxxxxxxxx89d36a4-917c-4165-ba6c-78073a608e58.vcf</href>
		<propstat>
			<prop />
			<status>HTTP/1.1 200 OK</status>
		</propstat>
		<propstat>
			<prop>
				<CR:supported-address-data />
			</prop>
			<status>HTTP/1.1 404 Not Found</status>
		</propstat>
	</response>
</multistatus>


"))
2019.04.17 14:35:59:391 : Discovery module : debug mode : response code : (new Number(207))
```
When I click on synchronize calendar
```
2019.04.17 14:48:24:017 : etecon : Synchronization not tried
2019.04.17 14:48:24:019 : All synchronizations finished
```
The problem of missing cardDav v4 option does not occur when I use my nextcloud instance as carddav remote, so it definitely seems to be related to what etesync-dav/radicale reports to cardbook

Manjaro
Thunderbird 66.6.1
Cardbook 35.6
etesync-dav 0.5.0
(official etesync server)

**Comment by jodojodo** [comment] 2019-04-27 00:41
I have a similar issue where only contacs without a stored photo were synced. When trying to sync a contact from the server that stored a photo, I get the following error:

> 2019.04.27 02:34:52:556 : Adressbuch Jonas: Fehler beim Parsen des Kontakts: 
InvalidCharacterError: String contains an invalid character 
BEGIN:VCARD
VERSION:4.0
PRODID:-//EteSync//com.etesync.syncadapter/1.4.0 ez-vcard/0.10.5
UID:67a814b4-057b-45dd-9182-fa63606f9532
ADR;LABEL="Leverkusen, Germany";TYPE=home:;;;Leverkusen;;;Germany
BDAY:1[BIRTHDAY]
EMAIL;TYPE=work:[EMAIL]
FN:[NAME]
N:[MNAME];[FNAME];;;
PHOTO:data:image/jpeg\;base64
REV:20190423T085522Z
TEL;TYPE=cell:[TEL]
davdroid1.TEL;TYPE=x-tablet:[TEL]
TEL;TYPE=home:[TEL]
TEL;TYPE=work:[TEL]
davdroid1.X-ABLABEL:Tablet
END:VCARD


I have removed all personal details and inserted placeholder in brackets [NAME], [TEL], etc.

**Comment by arsylum** [comment] 2019-05-02 21:41
So it seems that etesync-dav never had proper support for CardDav v4, contrary to the setup instructions for CardBook in the readme. I am surprised that it was anyway working for me for a long time with the "sloppy" version of CardBook that just assumed v4 support. I guess I have never added contact images in this address book.

Its a shame I would really like to stick with v4 since it also seems to be what the Lineage Contacts App seems to do natively (without an option to change it?)

I guess I will try migrating to v3 and see if that works without trouble.

**Comment by tasn** [comment] 2019-05-03 08:16
It's not lineage that insists on v4, it's actually EteSync on Android!

See #66 for more details, but essentially there's no going around it, we gotta fix Radicale.

As for your comment: it indeed seems like etesync-dav never had proper support for v4, although in practice it works and worked just fine (images included for all I remember with my tests). The CardBook instructions were based on my experiences.
The reason why it was working regardless is that v4 is quite similar and mostly compatible with v3, so when cardbook accidentally used v4 with Radicale it just worked.

**Comment by stevesbrain** [comment] 2019-07-16 10:03
Based on [this issue](https://gitlab.com/CardBook/CardBook/issues/634) it seems that the problem is that the image data is not included; it's just text. Cardbook doesn't know how to handle this. Is etesync-dav planning on including images at all, or can we just drop the image field then?

**Comment by tasn** [comment] 2019-07-16 10:21
I just replied there. My reply:

> It's actually a problem with EteSync, not CardBook. We use Radicale as a DAV server and it only supports vCard 3.0. Though it doesn't error when you pass it vCard 4.0 entries. It then pushes them out to clients (like CardBook) with almost any change. Unfortunately, the tiny change that it does make is break some fields (like Photo) where the format has changed between 3 and 4.

I think the easiest solution now, as you suggested, is to just filter out this field. It's not really a solution, especially since other fields could potentially be problematic, but I think it should fix 99% of the cases. Would you be able to test a fixed version if I make one?

Thanks!

**Comment by stevesbrain** [comment] 2019-07-16 10:25
@tasn Certainly happy to test out a fixed version :) As far as vs. upstream goes, I can receive images added via DavDroid into Radicale server -> Cardbook under v4.0, but I can't add images and sync back the other way. But yes, more  relevantly, I would be happy with a version of etesync-dav which ignores image field, and I'd be happy to test :)

**Comment by tasn** [comment] 2019-07-16 12:47
Could you please try the changes from the latest commit in this branch: https://github.com/etesync/etesync-dav/tree/photo

You can either just copy the changed file to your installed python path, or just install this branch directly with pip.

I tested it locally and it seems to work.

Thanks!

**Comment by stevesbrain** [comment] 2019-07-16 13:03
Awesome, will give that a test in the next 24 hours and let you know!

**Comment by stevesbrain** [comment] 2019-07-17 02:34
Can confirm @tasn that this does allow all contacts to appear; the only disclaimer would be that editing them locally overwrites the image (i.e. pushes an image removal for that contact) :)

**Comment by tasn** [comment] 2019-07-17 06:59
Thanks for testing! This is indeed an unfortunate limitation of this change. However fixing it is not trivial. The problem is the same problem that prevents us from serving it, the library used by radicale doesn't correctly serialize this field, which means it can't be properly written to etesync (which also uses vCard internally).

I'll have a think, but I think I will release a version with this limitation, so at least sync works. The nice thing about etesync is that history is retained, so no information will be lost and people will always be able to bring back the image.

**Comment by stevesbrain** [comment] 2019-07-18 10:17
Yeah, definitely agreed - releasing with the limitation is a better option, because at least folks can choose to use it as-is, or use it read-only (as the Thunderbird extension supports)  :) Appreciate the option and the explanation :)

**Comment by tasn** [comment] 2019-07-18 11:42
I'm going to close this one and release a version now. I guess the actual syncing of PHOTO is part of #66 .

**Closed by tasn** 2019-07-18 11:42 UTC
