### ISSUE TITLE
TbSync throws 500 -- Conflict in etesync-dav

### ISSUE THREAD

**Issue by plague-doctor** [etesync/etesync-dav#193] opened 2020-12-22 21:23 UTC
```
URL:
https://etesync-dav.domain.com/username/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

Response:
A server error occurred.  Please contact the administrator.
```

The etesync-dav error:
```
etesync-dav       | [2020-12-23 08:21:15 +1100] [7/Thread-3] [ERROR] Conflict
etesync-dav       | Traceback (most recent call last):
etesync-dav       |   File "etesync_dav/radicale/storage.py", line 84, in run
etesync-dav       |   File "etesync_dav/local_cache/__init__.py", line 92, in sync
etesync-dav       |   File "etesync_dav/local_cache/__init__.py", line 157, in sync_collection
etesync-dav       |   File "etesync_dav/local_cache/__init__.py", line 220, in push_collection
etesync-dav       |   File "etebase/__init__.py", line 294, in batch
etesync-dav       | etebase_python.Error: Conflict
etesync-dav       | [2020-12-23 08:21:15 +1100] [7/Thread-5] [ERROR] An exception occurred during PROPFIND request on '/username/': Conflict
```

When I click `Syncronize now` a few times it does finally connect and pulls changes. However I am unable to save any events/tasks from the Thunderbird back to etesync-server. It always fails...

Versions I use:
etesync-server: 0.5.1
etesync-dav: 0.30.6

**Comment by tasn** [comment] 2020-12-23 10:46
If you can come to https://www.etesync.com/community-chat/ that would be great, because we can probably figure it out quite quickly with some hands-on debugging.

**Comment by jdckr** [comment] 2020-12-23 11:31
Sounds similar to #189.

**Comment by plague-doctor** [comment] 2020-12-23 23:24
@jdckr nope, I do not go through the firewall or even through a router.

**Comment by tasn** [comment] 2020-12-24 15:34
@jdckr, I think the symptom is the same, and the cause may be similar. If I had to guess: for whatever reason an item was uploaded, but then not marked as uploaded locally, and that's causing it issues for whatever reason. Though it really shouldn't, which is why I'm confused. That's why I would like to have more checks done.

**Comment by phngs** [comment] 2020-12-28 13:23
Hi, I might have a similar issue. Using etesync-dav 0.30.6 and Provider for CalDAV & CardDAV 1.24 in Thunderbird when syncing Contacts, while Calendar and Tasks work fine. Have the same issue on two Windows machines. Android sync works fine. I just started to use etesync a few days ago it worked fine with the initial contacts imported from Google but I changed some of them, threw a few out and so on. Its I think 339 contacts, the first 300 in batches of 50 seem to work fine. Error message is in the last 39:

```
URL:
https://localhost:37358/p***s/c***L/ (REPORT)

Request:
<card:addressbook-multiget xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:prop><d:getetag /><card:address-data /></d:prop><d:href>/p***s/c***L/b***J.vcf</d:href>***</card:addressbook-multiget>

Response:
A server error occurred.  Please contact the administrator.
```

**Comment by plague-doctor** [comment] 2020-12-28 21:47
@phngs  Use latest release of etesync-server. This bug has been fixed.

**Comment by phngs** [comment] 2020-12-29 05:27
Thanks for the advise @plague-doctor, but I am using the paid hosted version from etesync, therefore I would expect it to be the latest version.

**Comment by tasn** [comment] 2020-12-31 11:03
@phngs, yeah, that would be the latest version. Please come join us at https://www.etesync.com/community-chat/ and we can help you figure it out. Your issue seems to be different.

As for this ticket, I'm closing it, as the underlying issue has been fixed on the server side.

**Closed by tasn** 2020-12-31 11:03 UTC
