### ISSUE TITLE
Dav exe file marked as malicious

### ISSUE THREAD

**Issue by xunil89** [etesync/etesync-dav#194] opened 2020-12-31 09:42 UTC
The file etesync-dav.exe v0.30.6 downloaded from your repo is marked as malicious by firefox and 26 antivirus! How come?
[https://www.virustotal.com/gui/file/c8dd38618ba4920e40f8e98471a59383c4d6cfe576604f86c5e4635b4447f722/](url)

**Comment by tasn** [comment] 2020-12-31 09:45
Duplicate of #190. Short answer: because the damn anti virus companies are sloppy and they just mark a lot of things. It sometimes gets flagged and sometimes doesn't. :|

See #190. We will probably address it by signing the binaries at some point.

**Comment by xunil89** [comment] 2020-12-31 09:51
Unfortunately I don't have enough computer knowledge to evaluate the source code, even if it seems quite unlikely that an opensource software on github has malicious code. But the high positivity of the file forces me to desist from installing it for safety.

**Comment by tasn** [comment] 2020-12-31 09:53
I understand, that's a reasonable approach.

**Comment by tx3eh8IUD1** [comment] 2020-12-31 12:14
I have the same issue. When I download the file, firefox marks it as malicious:
![image](https://user-images.githubusercontent.com/6958661/103410093-0b1d0580-4b6a-11eb-9b4b-9938b7e51647.png)

**Comment by xunil89** [comment] 2020-12-31 12:17
> I have the same issue. When I download the file, firefox marks it as malicious:
> ![image](https://user-images.githubusercontent.com/6958661/103410093-0b1d0580-4b6a-11eb-9b4b-9938b7e51647.png)
> 
> Affects versions 0.30.6 and 0.30.5 but **not ** 0.30.4
> 

To tell the truth they are all "infected" some more or less, the last one is the one with the most reports

**Comment by tasn** [comment] 2020-12-31 12:21
> To tell the truth they are all "infected" some more or less, the last one is the one with the most reports

Which just comes to show how unreliable all of these virus checkers are. :(

Let's continue the discussion in #190, as this one is a duplicate.

**Closed by tasn** 2020-12-31 12:21 UTC
Labels: duplicate
