### ISSUE TITLE
Mac setup issues

### ISSUE THREAD

**Issue by dfalling** [etesync/etesync-dav#68] opened 2019-05-17 22:44 UTC
Hiya, I'm having issues following the documentation for setup on a Mac.

### Problem 1: creating certificate with tool:
```bash
❯ ./etesync-dav-certgen --trust-cert
Traceback (most recent call last):
  File "./etesync-dav-certgen", line 16, in <module>
    from etesync_dav.config import CONFIG_DIR
ModuleNotFoundError: No module named 'etesync_dav'
```

I followed the manual steps instead.

### Problem 2: I can't add CalDAV or CardDAV accounts:
I entered the exact information provided by `etesync-dav manage get <myuser>` and the documentation, but consistently get an `Unable to verify account name or password` error.

How do I go about troubleshooting this?

**Comment by tasn** [comment] 2019-05-21 14:23
Sorry for the slow response. Github notifications has been very buggy for me for the last month or so. They just don't show anymore. :|

Problem 1: oh, it looks like certgen depends on the EteSync package being installed. I really need to merge it into the single binary as per #56.

Problem 2: please contact me by email (my first name at etesync.com) and I'll try to help you. Not sure what issue you may be experiencing and would be easier to investigate there.

I'm closing this ticket as I believe the first is kind of a duplicate of #56 and the second is a troubleshooting issue rather than an actual bug. Please, in the future, open separate tickets for separate issues, much easier to keep things under control this way. :)

**Closed by tasn** 2019-05-21 14:23 UTC
