### ISSUE TITLE
Cannot add calendars into Evolution

### ISSUE THREAD

**Issue by trymeouteh** [etesync/etesync-dav#123] opened 2020-04-08 04:03 UTC
When I go to File->New->Calendar and change it to CalDav, set the URL to http://localhost:37358/john@gmail.com/ and when I click on Find Calendars, I copy the password from the http://localhost:37358/ page and paste it into the password popup box. But it does not work and always rejects the password. When I click cancel the Find Calendars list is empty. I am running the etesync-dav client in the background.

I am on Linux Mint 19.3 using Evolution 3.28.5-0ubuntu0.18.04.1

**Comment by Philipp0205** [comment] 2020-06-01 07:10
Same for me: Ubuntu 20.10. In Thunderbird everything workds fine.

**Comment by tasn** [comment] 2020-06-01 07:20
@Philipp0205 did you follow the new (very recently changed) instructions from the README? Same to you @trymeouteh.
You can now just add the whole collection at once instead of one calendar at the time, and I tested it as recently as Thursday.

**Comment by Philipp0205** [comment] 2020-06-01 07:32
@tasn Yes I followed "Collection Account" approach. I checked the usual errors like not using the DAV PW as well. 

![image](https://user-images.githubusercontent.com/36603238/83386158-d33ebb80-a3ea-11ea-8886-2fdf3d3b2a7d.png)

**Comment by tasn** [comment] 2020-06-01 09:33
What version of etesync-dav? Additionally, could you maybe try `http://localhost:37358/YOUREMAIL/` in the serer field?

**Comment by Philipp0205** [comment] 2020-06-02 07:49
Thanks for your help! 

EteSync DAV version:  0.17.1
Radicale version:  2.1.11

I tried `http://localhost:37358/YOUREMAIL/` but no changes in behavior. It's not too serious for me because I use Thunderbird and that works like a charm.

**Comment by tasn** [comment] 2020-06-02 08:04
Anything in the etesync-dav output when it fails? What about if you run `etesync-dav -D`? I wonder what errors it shows.

**Comment by Philipp0205** [comment] 2020-06-04 15:34
Yes there seems to be an error:
```
7f13f59c3700] INFO: Collection read 417 items in 0.823956 sec from philippk@mailbox.org/226b87c97085df4216589a296bc7f809dd5d5a122657bf76f0468c0feaf8dfa4
[7f13f59c3700] ERROR: An exception occurred during PROPFIND request on '/philippk@mailbox.org/': 'VCARD components must contain at least 1 FN'
Traceback (most recent call last):
  File "site-packages/radicale/__init__.py", line 332, in __call__
  File "site-packages/radicale/__init__.py", line 505, in _handle_request
  File "site-packages/radicale/__init__.py", line 813, in do_PROPFIND
  File "site-packages/radicale/xmlutils.py", line 812, in propfind
  File "site-packages/radicale/xmlutils.py", line 985, in _propfind_response
  File "site-packages/etesync_dav/radicale/storage.py", line 598, in serialize
  File "site-packages/etesync_dav/radicale/storage.py", line 598, in <listcomp>
  File "site-packages/vobject/base.py", line 254, in serialize
  File "site-packages/vobject/behavior.py", line 157, in serialize
  File "site-packages/vobject/behavior.py", line 93, in validate
vobject.base.ValidateError: 'VCARD components must contain at least 1 FN'
[7f13f59c3700] INFO: PROPFIND request for '/.well-known/caldav' with depth '0' received from 127.0.0.1 using 'Evolution/3.36.2'
[7f13f59c3700] DEBUG: Request headers:
{'CONTENT_LENGTH': '227',
 'CONTENT_TYPE': 'application/xml; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-gb, en;q=0.9, en;q=0.8',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'close',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': 'localhost:37358',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'Evolution/3.36.2',
 'PATH_INFO': '/.well-known/caldav',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '37358',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7f13f6f47730>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7f13f59c3700] DEBUG: Sanitized script name: ''
[7f13f59c3700] DEBUG: Sanitized path: '/.well-known/caldav'
[7f13f59c3700] DEBUG: Response content:
The requested resource could not be found.
[7f13f59c3700] INFO: PROPFIND response status for '/.well-known/caldav' with depth '0' in 0.001 seconds: 404 Not Found
[7f13f59c3700] INFO: PROPFIND request for '/.well-known/carddav' with depth '0' received from 127.0.0.1 using 'Evolution/3.36.2'
[7f13f59c3700] DEBUG: Request headers:
{'CONTENT_LENGTH': '196',
 'CONTENT_TYPE': 'application/xml; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-gb, en;q=0.9, en;q=0.8',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'close',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': 'localhost:37358',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'Evolution/3.36.2',
 'PATH_INFO': '/.well-known/carddav',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '37358',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7f13f6f47730>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7f13f59c3700] DEBUG: Sanitized script name: ''
[7f13f59c3700] DEBUG: Sanitized path: '/.well-known/carddav'
[7f13f59c3700] DEBUG: Response content:
The requested resource could not be found.
[7f13f59c3700] INFO: PROPFIND response status for '/.well-known/carddav' with depth '0' in 0.001 seconds: 404 Not Found
```

**Comment by Philipp0205** [comment] 2020-06-04 15:40
Yes there seems to be an error: 
https://pastebin.com/9g4U4yAR

**Comment by tasn** [comment] 2020-06-07 14:35
Could you try again with 0.18.0? A few things changed there. Though this error is quite weird... What happens hen you log into https://client.etesync.com do you see any errors showing up (top right corner)? At the moment etesync-dav fatally fails on data parse errors, so maybe that's what is going on.

**Comment by Philipp0205** [comment] 2020-06-08 09:10
Unfortunately no difference with 0.18.0. When I login to the website everything works fine, no errors. I use it in thunderbird (same machine) and my android phone and everything works perfectly there as well. 

I debugged it again and this seems to be appearing: 
```
2020-06-08 11:07:55 +0200] [48274/Thread-31] [ERROR] An exception occurred during PROPFIND request on '/myemail@mailbox.org/': Failed to serialize item 'c67df6d6cf83bb079a5ab2a3b6681febd6900b64b4a517f4026435417f7dde71.vcf' from 'myemail@mailbox.org/226b87c97085df4216589a296bc7f809dd5d5a122657bf76f0468c0feaf8dfa4': 'VCARD components must contain at least 1 FN'
```

**Comment by tasn** [comment] 2020-06-08 12:00
OK, the problem is that you have a malformed vcard. See the related ticket on the radicale tracker: https://github.com/Kozea/Radicale/issues/830
I guess the easiest bet is to find this malformed vcard and figure out how it came to be...

Could you maybe try to go to https://client.etesync.com and see if you have any contacts with no name in the address book tab? I think that should be a sufficient place to start.

**Comment by Philipp0205** [comment] 2020-06-11 09:46
Ok! It was a contact with no name. At first this seemed unrelated to me but now it totally makes sense. Thank you very much!

**Comment by tasn** [comment] 2020-06-11 09:51
Did this fix things? I wonder what created it without a name in the first place... Could you maybe open the web client and from the change journal of the item share the "PRODID" from when it was created?

Thanks!

**Comment by Philipp0205** [comment] 2020-06-11 10:00
Yes this fixed it! Unfortunately I deleted the contact book and reimported all contacts. But the wrong contact was created years ago and etesync was not involved :) The contact list has a long history with different applications and somewhere along the way this contact got inserted.

**Comment by tasn** [comment] 2020-06-11 10:01
Gotcha, thanks! I'm closing this ticket then.

**Closed by tasn** 2020-06-11 10:01 UTC
