### ISSUE TITLE
Docker hangs during build

### ISSUE THREAD

**Issue by patogit** [etesync/etesync-dav#23] opened 2018-08-12 23:03 UTC
Tried setting up with Docker, no luck, it's been stuck for more than 20 minutes on the last line, trying to realize that it's supposed to download an 18KB file:

```
[user@system Apps]$ sudo systemctl start docker
[sudo] password for user: 
[user@system Apps]$ cd EteSync
[user@system EteSync]$ git clone https://github.com/etesync/etesync-dav.git
Cloning into 'etesync-dav'...
remote: Counting objects: 160, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 160 (delta 4), reused 4 (delta 2), pack-reused 151
Receiving objects: 100% (160/160), 44.40 KiB | 129.00 KiB/s, done.
Resolving deltas: 100% (79/79), done.
[user@system EteSync]$ ls
etesync-dav
[user@system EteSync]$ cd etesync-dav/
[user@system etesync-dav]$ ls
ChangeLog.md          Dockerfile   MANIFEST.in       scripts
DESCRIPTION.rst       etesync_dav  README.md         setup.py
docker-entrypoint.sh  LICENSE      requirements.txt
[user@system etesync-dav]$ docker build . -t etesync-dav:latest
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied 
context canceled
[user@system etesync-dav]$ sudo !!
sudo docker build . -t etesync-dav:latest
Sending build context to Docker daemon  163.8kB
Step 1/10 : FROM python:3.6
3.6: Pulling from library/python
55cbf04beb70: Pull complete 
1607093a898c: Pull complete 
9a8ea045c926: Pull complete 
d4eee24d4dac: Pull complete 
b59856e9f0ab: Pull complete 
b023afffd10b: Pull complete 
4d4eb448d315: Pull complete 
c4eb58602129: Pull complete 
598629fb90fc: Pull complete 
Digest: sha256:b96b5eecbb15cc6dc38653d8dac5499955c6088a66f4a62465efa01113c9895c
Status: Downloaded newer image for python:3.6
 ---> d49c41b6e6c4
Step 2/10 : ENV ETESYNC_CONFIG_DIR "/data"
 ---> Running in 5cda9a7dbaa3
Removing intermediate container 5cda9a7dbaa3
 ---> ad30c46b028b
Step 3/10 : ENV ETESYNC_LISTEN_ADDRESS "0.0.0.0"
 ---> Running in eb9f7dcbedbd
Removing intermediate container eb9f7dcbedbd
 ---> 75301db59595
Step 4/10 : ENV ETESYNC_LISTEN_PORT "37358"
 ---> Running in cb93c699779f
Removing intermediate container cb93c699779f
 ---> f3db52175839
Step 5/10 : COPY . /tmp
 ---> 194a457aa87e
Step 6/10 : RUN cd /tmp && python setup.py install
 ---> Running in dd5912dbe377
running install
running bdist_egg
running egg_info
creating etesync_dav.egg-info
writing etesync_dav.egg-info/PKG-INFO
writing dependency_links to etesync_dav.egg-info/dependency_links.txt
writing requirements to etesync_dav.egg-info/requires.txt
writing top-level names to etesync_dav.egg-info/top_level.txt
writing manifest file 'etesync_dav.egg-info/SOURCES.txt'
reading manifest file 'etesync_dav.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'etesync_dav.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/etesync_dav
copying etesync_dav/config.py -> build/lib/etesync_dav
copying etesync_dav/__init__.py -> build/lib/etesync_dav
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/etesync_dav
copying build/lib/etesync_dav/config.py -> build/bdist.linux-x86_64/egg/etesync_dav
copying build/lib/etesync_dav/__init__.py -> build/bdist.linux-x86_64/egg/etesync_dav
byte-compiling build/bdist.linux-x86_64/egg/etesync_dav/config.py to config.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/etesync_dav/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.6
copying and adjusting scripts/etesync-dav -> build/scripts-3.6
copying and adjusting scripts/etesync-dav-manage -> build/scripts-3.6
changing mode of build/scripts-3.6/etesync-dav from 644 to 755
changing mode of build/scripts-3.6/etesync-dav-manage from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/etesync-dav -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/etesync-dav-manage -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/etesync-dav to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/etesync-dav-manage to 755
copying etesync_dav.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying etesync_dav.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying etesync_dav.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying etesync_dav.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying etesync_dav.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/etesync_dav-0.1.5-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing etesync_dav-0.1.5-py3.6.egg
Copying etesync_dav-0.1.5-py3.6.egg to /usr/local/lib/python3.6/site-packages
Adding etesync-dav 0.1.5 to easy-install.pth file
Installing etesync-dav script to /usr/local/bin
Installing etesync-dav-manage script to /usr/local/bin

Installed /usr/local/lib/python3.6/site-packages/etesync_dav-0.1.5-py3.6.egg
Processing dependencies for etesync-dav==0.1.5
Searching for radicale_storage_etesync>=0.1.4
Reading https://pypi.org/simple/radicale_storage_etesync/
```

**Comment by tasn** [comment] 2018-08-13 10:58
CC @dan-v 

I don't know much about docker unfortunately.

**Comment by dan-v** [comment] 2018-08-13 18:10
Hmm. I'm not able to reproduce this issue of it hanging. 

But I haven't actually tried to build in a few months and I am seeing an issue now.

```
python setup.py install
...
error: python-dateutil 2.7.3 is installed but python-dateutil==2.6.1 is required by {'Radicale'}
The command '/bin/sh -c cd /tmp && python setup.py install' returned a non-zero code: 1
```

Looks like Radicale package was depending on vobject which was depending on an older version of python-dateutil. They have apparently forked vobject (https://github.com/Kozea/Radicale/commit/126a31c82abaf64ff27fc1bb5844a64a3b4e85f7) but haven't released a new version since that change. I can workaround it by adding master branch of Radicale 'git+git://github.com/Kozea/Radicale@master#egg=Radicale' into requirements.txt file, pip installing that, and then running setup.py install. Not sure what is really the best way to deal with this situation.

@tasn - as a side note it might make sense to publish a docker image so that people don't have to build it themselves, which would reduce the friction of using this even further. I can help with that if you'd like.

**Comment by tasn** [comment] 2018-08-13 18:58
I just updated all of the deps, including vobject (and pushed a more recent version of everything so it's pulled), so I don't see why Radicale is still complaining.
More specifically, vobject released a few versions in the last few months. Regardless, at least here, the version mismatches are warnings for "pip install etesync-dav" rather than failures (maybe it's a different case for setup.py install?) and things work.

Docker: help would be appreciated. Drop me a line via email so we can chat? tom @ the domain of the website. I guess also switching to pip install rather than this will also solve this problem.

**Comment by dan-v** [comment] 2018-08-13 19:10
The problem appears to be that in the 2.1.9 version of Radicale it has explicitly pinned to vobject==0.9.5 and python-dateutil=2.6.1: https://github.com/Kozea/Radicale/blob/ae8e10d90085f4247f9ae2156e4387c6d1f418a5/setup.py#L69. This has been fixed on master branch: https://github.com/Kozea/Radicale/blob/master/setup.py#L69

**Comment by tasn** [comment] 2018-08-13 19:14
I see. Well, all we can do is wait anyway...

I'd say, let's commence with the published script which works around this. Or maybe even change the one in the repo to just run pip install anyway and have a Dockerfile-dev alternative?

**Comment by dan-v** [comment] 2018-08-13 19:32
I think the approach of moving Dockerfile to pip install is the way to go (just verified this works). I think in the original PR I was bumping into issues with pip install, so I decided to go with this approach. I'll send a PR with this change.

**Comment by tasn** [comment] 2018-08-13 19:38
Sweet, looking forward!

@patogit, I'd guess it was maybe a one time thing. Please verify and let us know.

**Comment by patogit** [comment] 2018-08-17 02:05
I just tested again. This time it hung one line after the first time, in other words, it identified the file to download, a 6.2KB file, but didn't move beyond that. As a test, I activated a VPN connection and tried again, and this time it worked all the way through. Details: I am connecting from a mesh network in a  small rural community in Ecuador. I connected to a VPN that exits in Miami, USA. In case it's useful for triangulating the cause, sometimes Telegram is slow and I connect to a VPN that exits in Costa Rica, so maybe this is something about using ports besides 80 for international internet traffic? Wild guess.

**Comment by tasn** [comment] 2018-08-17 07:55
I think the file fetching is on 443 (https).

I'm not sure what your problem is, but it definitely sounds like a networking error with your mesh network rather with our (it's not even our) infrastructure.

I'm therefore closing this ticket, because it's out of scope and out of our control. If you think I'm wrong in doing so, please reopen and explain.

Glad to hear you have a workaround.

**Closed by tasn** 2018-08-17 07:55 UTC
