### ISSUE TITLE
0.33.4 fails to run when `ETESYNC_NO_WEBUI` env var is set

### ISSUE THREAD

**Issue by 0xedward** [etesync/etesync-dav#334] opened 2024-12-08 16:06 UTC
```
➜  /tmp export ETESYNC_NO_WEBUI=True
➜  /tmp ./linux-amd64-etesync-dav --version
EteSync DAV version:  0.33.4
Radicale version:  3.2.0
➜  /tmp ./linux-amd64-etesync-dav
[INFO] Loaded default config
[INFO] Loaded arguments
[INFO] Starting Radicale
[INFO] auth type is 'radicale.auth.htpasswd'
[INFO] storage type is 'etesync_dav.radicale.storage'
[INFO] rights type is 'etesync_dav.radicale.rights'
[CRITICAL] An exception occurred during server startup: Failed to load hook module 'radicale.hook.none': No module named 'radicale.hook.none'
```

The `radicale.web.none` path seems to exist on https://github.com/Kozea/Radicale/blob/master/radicale/web/none.py, so I'm guessing this is an issue with how the binary is built

**Comment by dstoeckel** [comment] 2024-12-22 12:01
Looks like a duplicate of #331

**Comment by tasn** [comment] 2024-12-22 13:58
Seems to be a problem with the pre-built binaries, right?

**Comment by dstoeckel** [comment] 2024-12-22 14:01
Indeed. I ran into this on my machine, too. I also tried packaging from newest Git master myself (not sure whether I did that correctly, basically installed into a venv and ran bundle.sh). Symptoms are the same. Running from the venv works fine.

**Comment by tasn** [comment] 2024-12-22 14:23
Fixed. Latest version will work (once CI finishes).

**Closed by tasn** 2024-12-22 14:23 UTC
